### PR TITLE
Checkout Button Schema

### PR DESCRIPTION
**Pull request by gealcan**
**What problem are you trying to solve?.**
Allow the checkout button redirect link to be edited via site editor.
Today, this behavior is controlled by the prop `finishShoppingButtonLink`(editable only via code).

It's interesting to go directly to the last checkout stage to speed up the checkout process.
However, when there is gift promotion, the only place where the user can choose the gift is on the first checkout stage:

Gifts-oficina

So it's useful for the commercial team to be able to change this behavior easily via site editor:
When there is a active gift promotion they would choose to send the user to the first checkout stage. Otherwise, they would choose the last checkout stage.

#### How to test it?
[Workspace](https://checkoutbuttonschema--oficinareserva.myvtex.com/) 
Admin -> CMS/Site editor -> Cabeçalho(Desktop/mobile)
--> Minicart Footer --> Botão de checkout

#### Screenshots or example usage:
Screenshot from 2022-11-07 14-02-45

Related to [#699](https://github.com/vtex-apps/store-discussion/issues/699)

### CODE REVIEW

**Comment by filipewl** [comment]
Hey @gealcan! We tried to access the workspace you created, but we're receiving the following error:
CleanShot 2022-12-19 at 18 20 36

Do you have any idea what's going on?

**Comment by filipewl** [comment]
Hey! How did you manage to select the Checkout Button in the Site Editor? We tried here, but when we add some product to the cart and open the mini cart, we can't select the button with the Site Editor's selector.

**Comment by jpesce** [comment]
Hi @filipewl, thanks for reviewing!

> Hey @gealcan! We tried to access the workspace you created, but we're receiving the following error
Do you have any idea what's going on?

Since this was implemented a long time ago, the workspace broke. I just created a new one with everything working. [Here it is.](https://checkoutbuttonschema--oficinareserva.myvtex.com/)

> How did you manage to select the Checkout Button in the Site Editor?

Here's a screen recording on how to reach it:

https://user-images.githubusercontent.com/1228352/208711914-8fe6f097-c709-47a9-8696-69a64588ef19.mp4

**Review by filipewl — APPROVED** [review]
Thanks for the PR and getting the workspace running again, and explaining how to edit it.
🙌 

I was able to edit the path for the Checkout Button via the Site Editor and confirmed it reflected in the store.

**Comment by filipewl** [comment]
Hey @gealcan and @jpesce! Due to some technical details, this PR seems stuck because we cannot get these 2 required checks running. I made a copy of this PR in #318, and over there, they're all passing, so we can proceed and merge that one. With that said, I'll close this one.

CleanShot 2022-12-22 at 15 23 21@2x

**Pull request closed without merging**
